#! /bin/sh

rm -rf ./src/*.so*
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a

rm -rf ./src/endianness.h

rm -rf ./src/*.o
rm -rf ./src/lapack/*.o
rm -rf ./src/utils/*.o

rm -rf src/Makevars

rm -rf ./src-*
rm -rf ./inst/lib
rm -rf ./autom4te.cache
